import { describe, expect, it } from 'vitest'
import { generateDevSnippet, extractCssEntries, matchesLinkEntry, generateBuildSnippet, type CssEntry } from '../src/generate.js'
import { normalizeOptions } from '../src/options.js'

describe('generateDevSnippet', () => {
  it('delegates to vite-tag and carries the generated header', () => {
    const snippet = generateDevSnippet()
    expect(snippet).toContain('Generated by vite-plugin-shopify-inline-styles. Do not edit.')
    expect(snippet).toContain("{% render 'vite-tag', entry: entry %}")
  })
})

const manifest = {
  'src/snippets/l-button.css': { file: 'l-button-D4k2.css', isEntry: true },
  'src/snippets/l-badge.css': { file: 'l-badge-Xk3D.css', isEntry: true },
  'src/sections/section.hero.scss': { file: 'section.hero-B2fK.css', isEntry: true },
  'src/entrypoints/main.ts': { file: 'main-Aa11.js', isEntry: true },
  'src/snippets/chunk.css': { file: 'chunk-Zz99.css' },
  'lib/outside.css': { file: 'outside-Qq00.css', isEntry: true },
}

describe('extractCssEntries', () => {
  const options = normalizeOptions({ linkEntries: ['l-button.css'] })

  it('keeps only CSS-source entrypoints under sourceCodeDir, sorted by key', () => {
    const entries = extractCssEntries(manifest, options)
    expect(entries.map((e) => e.key)).toEqual([
      'src/sections/section.hero.scss',
      'src/snippets/l-badge.css',
      'src/snippets/l-button.css',
    ])
  })

  it('maps aliasPath, output files, and link decision', () => {
    const entries = extractCssEntries(manifest, options)
    expect(entries[1]).toEqual({
      key: 'src/snippets/l-badge.css',
      aliasPath: 'snippets/l-badge.css',
      files: ['l-badge-Xk3D.css'],
      link: false,
    })
    expect(entries[2].link).toBe(true)
  })
})

describe('matchesLinkEntry', () => {
  it('matches by basename', () => {
    expect(matchesLinkEntry('snippets/l-button.css', ['l-button.css'])).toBe(true)
  })

  it('matches by full alias path with @/ or ~/ prefix', () => {
    expect(matchesLinkEntry('snippets/l-button.css', ['@/snippets/l-button.css'])).toBe(true)
    expect(matchesLinkEntry('snippets/l-button.css', ['~/snippets/l-button.css'])).toBe(true)
  })

  it('returns false when nothing matches', () => {
    expect(matchesLinkEntry('snippets/l-button.css', ['l-badge.css', '@/sections/x.css'])).toBe(false)
    expect(matchesLinkEntry('snippets/l-button.css', [])).toBe(false)
  })
})

describe('generateBuildSnippet', () => {
  const entries: CssEntry[] = [
    { key: 'src/sections/section.hero.scss', aliasPath: 'sections/section.hero.scss', files: ['section.hero-B2fK-p1.css', 'section.hero-B2fK-p2.css'], link: false },
    { key: 'src/snippets/l-badge.css', aliasPath: 'snippets/l-badge.css', files: ['l-badge-Xk3D.css'], link: false },
    { key: 'src/snippets/l-button.css', aliasPath: 'snippets/l-button.css', files: ['l-button-D4k2.css'], link: true },
  ]

  it('emits a when-branch with both alias forms per entry', () => {
    const snippet = generateBuildSnippet(entries)
    expect(snippet).toContain("when '@/snippets/l-badge.css' or '~/snippets/l-badge.css'")
    expect(snippet).toContain("assign vs_asset = 'l-badge-Xk3D.css'")
  })

  it('joins multi-part entries into a comma-separated assign', () => {
    const snippet = generateBuildSnippet(entries)
    expect(snippet).toContain("assign vs_asset = 'section.hero-B2fK-p1.css,section.hero-B2fK-p2.css'")
  })

  it('marks link entries with vs_link and leaves inline entries unmarked', () => {
    const snippet = generateBuildSnippet(entries)
    const buttonBranch = snippet.split("when '@/snippets/l-button.css'")[1].split('when')[0] ?? ''
    const badgeBranch = snippet.split("when '@/snippets/l-badge.css'")[1].split('when')[0] ?? ''
    expect(buttonBranch).toContain('assign vs_link = true')
    expect(badgeBranch).not.toContain('vs_link')
  })

  it('renders inline parts through one split-and-loop path', () => {
    const snippet = generateBuildSnippet(entries)
    expect(snippet).toContain("assign vs_parts = vs_asset | split: ','")
    expect(snippet).toContain('{%- for vs_part in vs_parts -%}')
    expect(snippet).toContain(
      '<style data-vite-style="{{ entry }}">{{ vs_part | inline_asset_content }}</style>',
    )
  })

  it('renders link fallback and unknown-entry branches', () => {
    const snippet = generateBuildSnippet(entries)
    expect(snippet).toContain('{{ vs_asset | asset_url | stylesheet_tag }}')
    expect(snippet).toContain("<!-- vite-style: unknown entry '{{ entry }}' -->")
  })

  it('emits no dedupe guard — Shopify render sandboxes increment counters, so one cannot work', () => {
    const snippet = generateBuildSnippet(entries)
    expect(snippet).not.toContain('increment')
    expect(snippet).not.toContain('vs_seen')
  })

  it('preserves entry order (already sorted upstream) and is deterministic', () => {
    const first = generateBuildSnippet(entries)
    const second = generateBuildSnippet(entries)
    expect(first).toBe(second)
    expect(first.indexOf('section.hero')).toBeLessThan(first.indexOf('l-badge'))
  })

  it('emits a comment-only snippet when there are no CSS entries', () => {
    const snippet = generateBuildSnippet([])
    expect(snippet).toContain('<!-- vite-style: no CSS entrypoints in build -->')
    expect(snippet).not.toContain('case entry')
  })
})
