import { describe, expect, it } from 'vitest'
import { generateDevSnippet, extractCssEntries, matchesLinkEntry } from '../src/generate.js'
import { normalizeOptions } from '../src/options.js'

describe('generateDevSnippet', () => {
  it('delegates to vite-tag and carries the generated header', () => {
    const snippet = generateDevSnippet()
    expect(snippet).toContain('Generated by vite-plugin-shopify-inline-styles. Do not edit.')
    expect(snippet).toContain("{% render 'vite-tag', entry: entry %}")
  })
})

const manifest = {
  'src/snippets/l-button.css': { file: 'l-button-D4k2.css', isEntry: true },
  'src/snippets/l-badge.css': { file: 'l-badge-Xk3D.css', isEntry: true },
  'src/sections/section.hero.scss': { file: 'section.hero-B2fK.css', isEntry: true },
  'src/entrypoints/main.ts': { file: 'main-Aa11.js', isEntry: true },
  'src/snippets/chunk.css': { file: 'chunk-Zz99.css' },
  'lib/outside.css': { file: 'outside-Qq00.css', isEntry: true },
}

describe('extractCssEntries', () => {
  const options = normalizeOptions({ linkEntries: ['l-button.css'] })

  it('keeps only CSS-source entrypoints under sourceCodeDir, sorted by key', () => {
    const entries = extractCssEntries(manifest, options)
    expect(entries.map((e) => e.key)).toEqual([
      'src/sections/section.hero.scss',
      'src/snippets/l-badge.css',
      'src/snippets/l-button.css',
    ])
  })

  it('maps aliasPath, output file, and link decision', () => {
    const entries = extractCssEntries(manifest, options)
    expect(entries[1]).toEqual({
      key: 'src/snippets/l-badge.css',
      aliasPath: 'snippets/l-badge.css',
      file: 'l-badge-Xk3D.css',
      link: false,
    })
    expect(entries[2].link).toBe(true)
  })
})

describe('matchesLinkEntry', () => {
  it('matches by basename', () => {
    expect(matchesLinkEntry('snippets/l-button.css', ['l-button.css'])).toBe(true)
  })

  it('matches by full alias path with @/ or ~/ prefix', () => {
    expect(matchesLinkEntry('snippets/l-button.css', ['@/snippets/l-button.css'])).toBe(true)
    expect(matchesLinkEntry('snippets/l-button.css', ['~/snippets/l-button.css'])).toBe(true)
  })

  it('returns false when nothing matches', () => {
    expect(matchesLinkEntry('snippets/l-button.css', ['l-badge.css', '@/sections/x.css'])).toBe(false)
    expect(matchesLinkEntry('snippets/l-button.css', [])).toBe(false)
  })
})
