import { describe, expect, it } from 'vitest'
import { generateDevSnippet } from '../src/generate.js'

describe('generateDevSnippet', () => {
  it('delegates to vite-tag and carries the generated header', () => {
    const snippet = generateDevSnippet()
    expect(snippet).toContain('Generated by vite-plugin-shopify-inline-styles. Do not edit.')
    expect(snippet).toContain("{% render 'vite-tag', entry: entry %}")
  })
})
