import path from 'node:path'
import type { ResolvedOptions } from './options.js'

const GENERATED_HEADER = `{% comment %}
  Generated by vite-plugin-shopify-inline-styles. Do not edit.
{% endcomment %}`

const CSS_EXTENSIONS = /\.(css|less|sass|scss|styl|stylus|pcss|postcss)$/

export interface ManifestChunk {
  file: string
  src?: string
  isEntry?: boolean
}

export interface CssEntry {
  /** Manifest key, e.g. 'src/snippets/l-badge.css' */
  key: string
  /** Path relative to sourceCodeDir, e.g. 'snippets/l-badge.css' */
  aliasPath: string
  /** Hashed output asset filenames — one, or several ≤15KB parts after auto-split */
  files: string[]
  /** Render as <link> instead of inline <style> */
  link: boolean
}

export function generateDevSnippet(): string {
  return `${GENERATED_HEADER}
{% render 'vite-tag', entry: entry %}
`
}

export function extractCssEntries(
  manifest: Record<string, ManifestChunk>,
  options: ResolvedOptions,
): CssEntry[] {
  const prefix = options.sourceCodeDir.replace(/^\.\//, '').replace(/\/$/, '') + '/'
  return Object.keys(manifest)
    .filter((key) => manifest[key].isEntry && CSS_EXTENSIONS.test(key) && key.startsWith(prefix))
    .sort()
    .map((key) => {
      const aliasPath = key.slice(prefix.length)
      return {
        key,
        aliasPath,
        files: [manifest[key].file],
        link: matchesLinkEntry(aliasPath, options.linkEntries),
      }
    })
}

export function matchesLinkEntry(aliasPath: string, linkEntries: string[]): boolean {
  const basename = path.posix.basename(aliasPath)
  return linkEntries.some((raw) => {
    const cleaned = raw.replace(/^[@~]\//, '')
    return cleaned === aliasPath || cleaned === basename
  })
}

export function generateBuildSnippet(entries: CssEntry[]): string {
  if (entries.length === 0) {
    return `${GENERATED_HEADER}
<!-- vite-style: no CSS entrypoints in build -->
`
  }

  // Each branch bumps a per-entry {% increment %} counter. Increment counters are the
  // one piece of state Liquid shares across {% render %} sandboxes, so the first render
  // of an entry on a page sees '0' and emits the tag; repeat renders see '1', '2', …
  // and emit nothing — one <style>/<link> per entry per page, no matter how many times
  // a component renders. The counter name must be a literal, hence one per branch.
  const branches = entries
    .map((entry, index) => {
      const lines = [
        `    when '@/${entry.aliasPath}' or '~/${entry.aliasPath}'`,
        `      assign vs_asset = '${entry.files.join(',')}'`,
        `      capture vs_seen`,
        `        increment vite_style_once_${index}`,
        `      endcapture`,
      ]
      if (entry.link) lines.push('      assign vs_link = true')
      return lines.join('\n')
    })
    .join('\n')

  return `${GENERATED_HEADER}
{%- liquid
  case entry
${branches}
  endcase
-%}
{%- if vs_asset == blank -%}
  <!-- vite-style: unknown entry '{{ entry }}' -->
{%- elsif vs_seen == '0' -%}
  {%- if vs_link -%}
    {{ vs_asset | asset_url | stylesheet_tag }}
  {%- else -%}
    {%- assign vs_parts = vs_asset | split: ',' -%}
    {%- for vs_part in vs_parts -%}
      <style data-vite-style="{{ entry }}">{{ vs_part | inline_asset_content }}</style>
    {%- endfor -%}
  {%- endif -%}
{%- endif -%}
`
}
