import path from 'node:path'
import type { ResolvedOptions } from './options.js'

const GENERATED_HEADER = `{% comment %}
  Generated by vite-plugin-shopify-inline-styles. Do not edit.
{% endcomment %}`

const CSS_EXTENSIONS = /\.(css|less|sass|scss|styl|stylus|pcss|postcss)$/

export interface ManifestChunk {
  file: string
  src?: string
  isEntry?: boolean
}

export interface CssEntry {
  /** Manifest key, e.g. 'src/snippets/l-badge.css' */
  key: string
  /** Path relative to sourceCodeDir, e.g. 'snippets/l-badge.css' */
  aliasPath: string
  /** Hashed output asset filename, e.g. 'l-badge-Xk3D.css' */
  file: string
  /** Render as <link> instead of inline <style> */
  link: boolean
}

export function generateDevSnippet(): string {
  return `${GENERATED_HEADER}
{% render 'vite-tag', entry: entry %}
`
}

export function extractCssEntries(
  manifest: Record<string, ManifestChunk>,
  options: ResolvedOptions,
): CssEntry[] {
  const prefix = options.sourceCodeDir.replace(/^\.\//, '').replace(/\/$/, '') + '/'
  return Object.keys(manifest)
    .filter((key) => manifest[key].isEntry && CSS_EXTENSIONS.test(key) && key.startsWith(prefix))
    .sort()
    .map((key) => {
      const aliasPath = key.slice(prefix.length)
      return {
        key,
        aliasPath,
        file: manifest[key].file,
        link: matchesLinkEntry(aliasPath, options.linkEntries),
      }
    })
}

export function matchesLinkEntry(aliasPath: string, linkEntries: string[]): boolean {
  const basename = path.posix.basename(aliasPath)
  return linkEntries.some((raw) => {
    const cleaned = raw.replace(/^[@~]\//, '')
    return cleaned === aliasPath || cleaned === basename
  })
}
