const GENERATED_HEADER = `{% comment %}
  Generated by vite-plugin-shopify-inline-styles. Do not edit.
{% endcomment %}`

export function generateDevSnippet(): string {
  return `${GENERATED_HEADER}
{% render 'vite-tag', entry: entry %}
`
}
